### ISSUE TITLE
drewr/postal

### ISSUE THREAD

**Issue by borkdude** [BrunoBonacci/graalvm-clojure#15]
I've been experimenting with drewr/postal to be able to send e-mails from a native-image.
So far it fails for me with:

```
#error {
 :cause "smtps"
 :via
 [{:type javax.mail.NoSuchProviderException
   :message "smtps"
   :at [javax.mail.Session getService "Session.java" 811]}]
```

I've tried adding `com.sun.mail.smtp.SMTPTransport` to the reflection config, but this didn't help.

**Comment by borkdude** [comment]
Useful comment from the graalvm slack:

> looks like smtps requires com.sun.mail.smtp.SMTPSSLTransport  instead of SMTPTransport

**Comment by borkdude** [comment]
Confirming that worked!

**Comment by BrunoBonacci** [comment]
Fantastic, would you be able to add an example?

**Comment by borkdude** [comment]
@BrunoBonacci I'm trying to add it to babashka: https://github.com/borkdude/babashka/
Once that's finished, I'll have a look if I can add a small example here.

**Comment by BrunoBonacci** [comment]
Hi Michiel,
that's great!

funny enough I was just watching your :ClojureD talk on Babashka this morning!! ;-)
Really great work!

**Comment by borkdude** [comment]
The only thing that I haven't mentioned in this issue is that you have to set the System property `postal.version` to something, else you'll get a `NullPointerException` in your GraalVM native-image binary.

I'm not going to spend any energy in it right now, because the above approach only works on java8 and not with java11 versions of GraalVM. Maybe I'll revisit in the future.
