### ISSUE TITLE
Create a status column per major GraalVM version

### ISSUE THREAD

**Issue by rafaeldelboni** [BrunoBonacci/graalvm-clojure#17]
With the new [GraalVM 20.1 release](https://www.graalvm.org/docs/release-notes/20_1/) would be nice to have a way to check how each major release compares with the older ones.

WDYT?

**Comment by BrunoBonacci** [comment]
Hi @rafaeldelboni 
that is a great idea, but we would need a way to easily retest all the projects automatically.
I've done this for the Clojure core [check here](https://github.com/BrunoBonacci/graalvm-clojure/blob/master/clojure/bin/build-all.sh)
but we would need something similar which runs all the projects.

That would be a really good contribution!!! (if you wish to make one ;-) )

**Comment by BrunoBonacci** [comment]
out of scope
