### ISSUE TITLE
Add a spec example project

### ISSUE THREAD

**Issue by danielcompton** [BrunoBonacci/graalvm-clojure#3]
Currently, you can't build a native-image that uses spec: https://github.com/oracle/graal/issues/1681. It could be good to add a small test project demonstrating that to test against.

**Comment by borkdude** [comment]
With clojure 1.10.2-alpha1 it should now be possible to use spec with native-image.

**Comment by BrunoBonacci** [comment]
Why? what did change to make that possible?

**Comment by borkdude** [comment]
@BrunoBonacci https://github.com/clojure/clojure/commit/f5403e9c666f3281fdb880cb2c21303c273eed2d

**Comment by jrwdunham** [comment]
I've created PR https://github.com/BrunoBonacci/graalvm-clojure/pull/21 that seems to show Graal native image working with Clojure 1.10.1 and spec.alpha 0.2.187. I have had trouble in the past doing this (with any version of Clojure) so I am wondering if this a false positive?

**Comment by borkdude** [comment]
Just updated to 1.10.2-alpha1 and it should work reliably.
