### ISSUE TITLE
Problem running the aws-api-s3

### ISSUE THREAD

**Issue by burinc** [BrunoBonacci/graalvm-clojure#31]
I am getting the following errors:

```
./aws-api-s3 
Exception in thread "main" clojure.lang.ExceptionInfo: Cannot find resource cognitect/aws/s3/service.edn. {}
	at cognitect.aws.service$service_description.invokeStatic(service.clj:31)
	at cognitect.aws.service$service_description.invoke(service.clj:28)
	at cognitect.aws.client.api$client.invokeStatic(api.clj:67)
	at cognitect.aws.client.api$client.invoke(api.clj:22)
	at simple.main$_main.invokeStatic(main.clj:8)
	at simple.main$_main.invoke(main.clj:7)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at simple.main.main(Unknown Source)
```
Not sure if anyone have idea about how to make this work.
I am guessing that it may have something to do with adding the following [config](https://www.graalvm.org/reference-manual/native-image/Resources/) as part of native-image generation.

My env:

```
graalvm-ce-java11-20.3.0
Clojure 1.10.1-rc2
Java 1.11.0
```

**Comment by BrunoBonacci** [comment]
Hi,

you need to make sure that the step `lein native-config` is executed before running `lein native`.
This step will execute the program with an agent and detect the configuration required, including the presence of the above file in the resource bundle.

For this reason, it is important that the `lein native-config` step does a full run of as many cases as possible in the program runtime. For example, before executing `lein native-config` ensure you have provided a valid set of keys using the environment variables:
```
$ export AWS_ACCESS_KEY_ID=xxx
$ export AWS_SECRET_ACCESS_KEY=yyy
$ export AWS_DEFAULT_REGION=us-west-2
```

**Comment by jeroenvandijk** [comment]
@BrunoBonacci Thanks! I have been able to use your example as the start for an `aws-api` Babashka Pod. I hope to publish it soon.

**Comment by burinc** [comment]
@BrunoBonacci 

Thanks I am able to get the result following your details.
One notes, it seems that I have to use only version of Java that comes with GRAALVM to compile the image to make this work during the `native-config` step.
e.g.
When trying with different version of Java, I am getting the following error:

```
 lein do clean, uberjar, native-config, native, run-native
Compiling simple.main
Created /Users/burinc/b12n/BrunoBonacci--graalvm-clojure/aws-api-s3/target/aws-api-s3-0.1.0-SNAPSHOT.jar
Created /Users/burinc/b12n/BrunoBonacci--graalvm-clojure/aws-api-s3/target/simple-main.jar
Error occurred during initialization of VM
Could not find agent library native-image-agent on the library path, with error: dlopen(libnative-image-agent.dylib, 1): image not found
```

Thanks

**Comment by BrunoBonacci** [comment]
I'm glad that you fixed the issue. 
in regards to the compilation note, you can compile the jar with any JVM (like openjdk) but to run the native image agent or builder you need a GraalVM.
