### ISSUE TITLE
Hiccup doesn't work with dynamic input.

### ISSUE THREAD

**Issue by borkdude** [BrunoBonacci/graalvm-clojure#33]
This is because hiccup relies on `eval` for compiling input. So hiccup only works when it's used in a "static" way.

**Comment by BrunoBonacci** [comment]
thanks for the info, I've added a note.

**Comment by borkdude** [comment]
@BrunoBonacci Actually I take that back. Hiccup works fine. It was an issue with sci + hiccup, not hiccup in general.

**Comment by borkdude** [comment]
The explanation is that hiccup does use `eval`, but only during macro-expansion. And I was triggering macro-expansion in sci, because I mapped the `html` macro inside the interpreter. Wrapping it with a function takes care of that issue.
