### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by kasajian** [BrunoBonacci/graalvm-clojure#38]
Please update Readme to indicate the final size of the executable, including the sizes of all dependencies.

If one were to create a demo using this tool, how much does the end-user need to download and install assuming no dependencies are pre-installed.

**Comment by BrunoBonacci** [comment]
Hi,
I think this is beyond the scope of this project.
The size can greatly change from platform to platform and from version to version of both Graalvm and the libraries compiled.

The objective of this repo is to help people to find the correct minimal configuration for each library they use and verify, fix compilation issues in isolation.

Adding the size is a piece of valuable information, however, to be thorough it would require automated builds in CI environment with multiple versions. I would be happy to accept PR for this.
