### ISSUE TITLE
Workaround for dynamic Var holding a SecureRandom instance

### ISSUE THREAD

**Issue by jimpil** [BrunoBonacci/graalvm-clojure#6]
Hi there,

First of all many thanks for this repo - it contains some super valuable information! I just wanted to say that I was recently trying to create a native-image for `cryptohash-clj`, and it turns out that the problem was statically initialised instances of `SecureRandom`. You see, the library has a dynamic Var initialised with an instance of SecureRandom, and no matter what I did, I wasn't able to generate a working image (I tried literally everything). I wrapped that instance in a `delay` ([see here](https://github.com/jimpil/cryptohash-clj/blob/6317a7226eefb77b80304fd76e8137f290ad534d/src/clojure/cryptohash_clj/globals.clj#L9)), and now the native-image is working as expected.    

I just thought you (or someone else) might find that information useful. 

Kind regards

**Comment by BrunoBonacci** [comment]
Hi @jimpil ,
thanks for the tip, for the Sercure initialization you should check the following links:
  - [JCA Security Services on Substrate VM](https://github.com/oracle/graal/blob/master/substratevm/JCA-SECURITY-SERVICES.md)
  - [Assisted Configuration of Native Image Builds](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md)

anyway, I think that your one is a neat trick, would you be able to make a hello-world project with your example and push it here as a PR?
More people could benefit from an example in a project.

**Comment by jimpil** [comment]
Hi @BrunoBonacci ,

Yeah, I did try re-initializing at runtime, `--enable-all-security-services`, and various other things, but nothing worked. I think the problem here is a combination of the dynamic Var (which can't be direct-linked) and the pre-initialised `SecureRandom` instance. 

I'll try to put together a tiny project to demonstrate by the end of the week. :+1: 

Kind regards

**Comment by BrunoBonacci** [comment]
example merged, thx
